language: node_js
node_js:
  - "10"
cache:
  yarn: true

install:
  - yarn install

script:
  - npm run build

deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  name: cjcj5438
  email: 1002931123@qq.com
  on:
    branch: master
